# Generated by Django 6.0.3 on 2026-04-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerShareRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_label",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("method", "Method"),
                            ("results", "Results"),
                            ("discussion", "Discussion"),
                            ("conclusion", "Conclusion"),
                            ("custom", "Custom section"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("section_text", models.TextField()),
                ("question", models.TextField(blank=True)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_requests",
                        to="core.document",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ai_contribution_score", models.IntegerField(default=0)),
                ("ai_score_detail", models.TextField(blank=True, default="{}")),
                ("scored", models.BooleanField(default=False)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "share_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.peersharerequest",
                    ),
                ),
            ],
        ),
    ]
