# Generated by Django 6.0.3 on 2026-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_teachercomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerfeedback",
            name="ai_feedback_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peerfeedback",
            name="ai_feedback_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="peerfeedback",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peerfeedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
