# Generated by Django 4.2.11 on 2026-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_preferred_language_feedbackreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peersharerequest",
            name="section_label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
